### ISSUE TITLE
Scoping Representations?

### ISSUE THREAD

**Issue by stacietaylorcima** [coyote-team/coyote#144]
Hey @subelsky & @flipsasser! I'm looking for a little direction here.

I am working on implementing a new scope for representations so that when they are queried, they are displayed grouped by metum, then sorted by index. 

**My question is, where would I do this? I understand how to build and apply the scope, but I'm not sure where to ensure all queries for representations respect the scope.** 

I found some scopes (in the Representation model, line 52 & 53) that looked like what I would want to modify, but they don't seem to be respected anywhere accept on a method called `best_representation`(on the Resource model, line 123) that is only called in one place (Resources show view, line 6). What is the purpose of `best_representation`? 

cc @sinabahram 

(My new scope might look something like this: `scope :by_metum_title_with_index, -> { joins(:metum).order("meta.title, representation.index ASC") }`)

**Comment by subelsky** [comment]
I believe the method you want is [default_scope](https://api.rubyonrails.org/classes/ActiveRecord/Scoping/Default/ClassMethods.html#method-i-default_scope) but I would tread carefully. I think that's a tool to use sparingly, in part because it violates the [principle of least surprise](https://en.wikipedia.org/wiki/Principle_of_least_astonishment) -- other developers building a feature that requires access to all `Representation` objects (for example, an archiving feature) might be surprised to realize that `Representation.all` was no longer giving them "all".)

**Comment by sinabahram** [comment]
This is why we decided not to make it the default scope, since Flip informs us that default scope is applied first, not last. If there was a default post-facto scope, that would be perfect. Mike, do you agree/disagree with this?

**Comment by subelsky** [comment]
I agree. So we'd have to find another design to fulfill the requirement behind the goal 'ensure all queries for representations respect the scope.'

**Comment by sinabahram** [comment]
To that end, Flip and Stacie were discussing updating RecordFilter to capture this ordinality sorting. Thoughts?
