### ISSUE TITLE
COYOTE link in top left corner sends to login page instead of home

### ISSUE THREAD

**Issue by alavatelliMCA** [coyote-team/coyote#160]
The link in the top left should send you to the dashboard when already logged in.

**Comment by sinabahram** [comment]
Stacie, please handle this one.

**Comment by stacietaylorcima** [comment]
Just took a look and did a little testing, but logging out for the night so I'm taking some notes here so I can get back at it tomorrow: 

It seems that when you're on any of the primary nav pages (Dashboard, Assignments, Resources, Descriptions, Members, Meta, Resource Groups), clicking the COYOTE logo will take you to the desired page, Dashboard (`organization_path`). However, when you're on any of the secondary pages (Support, Profile, Organizations) you are directed instead to the Home Page (`root_path`). 

```
      = link_to current_organization? ? current_organization : root_path, class: "nav-brand" do...

```

If I remove the conditional and only point to the `current_organization`, clicking the COYOTE logo from any of the primary nav pages still works, but clicking to access any of the secondary navigation pages gives me the following error: `Couldn't find Organization without an ID`. So, somehow, the secondary nav pages aren't registering that the organization id exists and that's why they're not fulfilling the conditional properly. Check out what's going on with the `_user_nav.html.slim`

**Comment by stacietaylorcima** [comment]
_This issue correlates with another issue (#126) that says "The navigation disappears on the user page"._

<hr>

The problem here is that all the "secondary navigation" pages (like, Support, Profile, Organizations, etc) aren't associated with a specific organization, they're associated with the user. 

So, if a user is on one of the main navigation pages (Resources, Descriptions, Meta, etc…) and they click COYOTE, they'll be directed to the desired page: Dashboard. However, if the user has multiple organizations, they have to first select the organization from the drop down THEN click the COYOTE to be directed to the dashboard. If they only have one organization, they don't have the option to select and are always directed to the home page. 

**Here are some potential fixes I am thinking about:** 

**Option 1**
- Pass URL param from org pages to secondary nav pages (like ?org_id=2)

**Option 2**
- Store a current_org_id cookie after selecting a different org in the nav

**Option 3**
- Have a default org at the db level to go back to from secondary nav pages.

<hr>

Any thoughts on how to best handle this issue? Thanks! @sinabahram @flipsasser

**Comment by sinabahram** [comment]
I’d be interested to know Flips’ thoughts here. #1 seems the easiest and most straight forward. I could see how #2 could have some elegance, though this information is session-based, so storing it in a cookie that would persist across logins seems like overkill. #3 seems too much like an unnecessary step of persistence. After all, this information is known and only needed at interaction time with the page, so #1 seems like the best strategy to me.

 

Thoughts?

**Comment by alavatelliMCA** [comment]
I'll note that when I navigate to Coyote in a new browser window while I'm already logged in I am also sent to the login page, but I see my name in the upper right. When I click login it takes me to the main dashboard page. This is a very low impact issue that should be last on the list of things to tackle.

**Comment by flipsasser** [comment]
Fixed this forever ago but didn't mark it as complete; it's complete
