### ISSUE TITLE
Coyote Style Guide

### ISSUE THREAD

**Issue by alavatelliMCA** [coyote-team/coyote#173]
I am posting the original Coyote style guide here. Please keep in mind that these designs are now a couple of years old so there have been many adjustments to accommodate content and data structures that have been updated in the new version. 

If in doubt about any element, please don't hesitate to reach out here or on slack.

[14 coyote design refinements.pdf](https://github.com/coyote-team/coyote/files/2340792/14.coyote.design.refinements.pdf)

**Comment by sinabahram** [comment]
Request: If we are going to use this as a hard reference, will it be possible to update these designs to bring them into synchronicity with current Coyote so there’s a very clear path for devs to follow?

**Comment by alavatelliMCA** [comment]
I don't think updating these files is a good use of time or budget, all design files look different in the live web context. This file is simply a style reference point, especially the first page of the designs which lays out scale, color, and overall aesthetic. The subsequent pages based on Coyote's original scope demonstrate scale and spacing relationships in context. They are useful, as long as everyone realizes it is for visual **style** reference material, not a visual design directive. Right now we are VERY close to matching these designs. It is looking great.

**Comment by sinabahram** [comment]
That is fair, but just so you know my side of it, it can be very frustrating to be asked to use them, but only sort of, kind of as a reference, but not exactly, etc. … I know what you mean, and I also agree with it, and I agree with the use of time/budget, but when we keep referring back to them repeatedly, it makes me think that maybe a separate design guide may be a good use of time later on, even if it’s not at all wireframes or anything.

 

This way, folks don’t have to overcome multiple levels of abstraction and cognitive dissonance to get on the same page about the design look/feel.

 

Just my $0.02 since this has now come up several times across different implementers on my end.
