### ISSUE TITLE
Scavenger Hunt Design - Typography

### ISSUE THREAD

**Issue by alavatelliMCA** [coyote-team/coyote#205]
The design really is still very close, but to best see any layout concerns let's first address the line spacing now that the font has been updated. This should just be making adjustments to match the design document typographic treatment.

**Comment by stacietaylorcima** [comment]
You got it! I've got some good line spacing fixes locally, but won't be able to push them up until tonight. Since I'm not going to push them until tonight, I'll try to drop in some other updates that will take it closer to the design guide. If I can get the PR approved and merged tonight (or early tomorrow morning), you'll be able to jump in and provide more detailed adjustments tomorrow! Go, team! cc @alavatelliMCA @sinabahram 

![scavenger hunt 1](https://user-images.githubusercontent.com/25017973/45314156-de9ad680-b4e5-11e8-9003-d23b6d0af8e8.png)

**Comment by alavatelliMCA** [comment]
A note for further refinement:
The start page is good for looking at the various type sizes and how they need to be normalized. Below is a side by side with original design doc: 

![screen shot 2018-09-13 at 12 01 22 pm](https://user-images.githubusercontent.com/8040710/45503544-c7115700-b74c-11e8-9454-490f6e0db7f0.png)
https://live.coyote.pics/scavenger/games/11

**Comment by stacietaylorcima** [comment]
Thanks, @alavatelliMCA! This should be a pretty easy fix. Staging is a bit more up to date with styles at this point than production by the way.

**Comment by alavatelliMCA** [comment]
After looking at the overall scale and spacing treatment against design files. Below are a few screens where type alignment is off, let's check after you've addressed the above as they may be remedied in the process.

https://live.coyote.pics/scavenger/games/11/finish
<img width="386" alt="screen shot 2018-09-13 at 9 28 22 am" src="https://user-images.githubusercontent.com/8040710/45504814-7bf94300-b750-11e8-9ec1-931bf3e27da6.png">

<img width="386" alt="screen shot 2018-09-13 at 9 28 05 am" src="https://user-images.githubusercontent.com/8040710/45505821-3b4ef900-b753-11e8-9777-7798b3452ca2.png">

<img width="385" alt="screen shot 2018-09-13 at 9 26 42 am" src="https://user-images.githubusercontent.com/8040710/45505863-54f04080-b753-11e8-92b9-c4c114d0fa5c.png">

**Comment by stacietaylorcima** [comment]
@alavatelliMCA Are you looking at staging?
