### ISSUE TITLE
Orange focus state clashes

### ISSUE THREAD

**Issue by alavatelliMCA** [coyote-team/coyote#216]
The focus state is an orange glow which looks a little insane on the pink, and just a bit ugly on the white background.

<img width="388" alt="screen shot 2018-09-13 at 9 27 37 am" src="https://user-images.githubusercontent.com/8040710/45504928-d4c8db80-b750-11e8-8a12-a84568514402.png">

<img width="386" alt="screen shot 2018-09-13 at 9 28 54 am" src="https://user-images.githubusercontent.com/8040710/45504936-d8f4f900-b750-11e8-9682-ec1e3e673ee2.png">

**Comment by sinabahram** [comment]
Sorry if I missed this, but is there a color already assigned for this in a visual design guide or do you have a specific color that you want this replaced with?

**Comment by stacietaylorcima** [comment]
I am re-opening this issue: 

**@alavatelliMCA and @sinabahram Can I get your thoughts on my message below?** 

I think that the magenta color being used on the MCA organization for Scavenger Hunt may need to be updated to meet accessibility requirements. Take a look at these details below and let me know if 1) I'm overlooking something and the magenta actually IS accessible and/or 2) what changes we should make to comply with accessibility requirements. 

I tried to see what the design guide included, but it didn't seem to have any indicator on the input. I am thinking we can start by updating MCA's color then find a focus indicator color that complies. OR do we have options other than the focus indicator that we'd like to use? 

**Current colors for MCA Scavenger Hunt:** 
- Magenta currently being used for MCA Scavenger Hunt color: #ff00ff
- White text when Scavenger Hunt is inverted: #ffffff 
- Blue focus ring: #00f

### Contrast Ratio for a magenta themed organization: 
**Magenta & white:** 
* 3.14:1
* NOT accessible. There is both large and small text displayed with this color scheme (white text on magenta background and magenta text on white background), so it's not an accessible choice. 

**Magenta & blue focus ring:** 
* 2.74:1
* The blue ring does NOT meet accessibility requirements on the magenta background. 

**White & blue focus ring:** 
* 8.59:1 
* The blue ring DOES meet accessibility standards on the white background.

**Comment by stacietaylorcima** [comment]
OH! If we replace the magenta with an accessible color, I could figure out how to make the focus indicator be white when the background is color and make the focus indicator the new color when the background is white. I was spending a bunch of time trying to find a focus indicator color that worked with both a new color and white and was having a hard time, but I think that could be a really great solution that wouldn't introduce any random colors into the theme! What do y'all think?

**Comment by sinabahram** [comment]
This sounds promising. I’m sure a white focus ring wouldn’t work well for all colors other than a white background, but it’s a step in the right direction. Also, we don’t have to solve this problem perfectly, only for the colors for the participating organizations. Can we gather said color list from MCA  et al.? Stacie, maybe you can manage that?

**Comment by alavatelliMCA** [comment]
Thank you. I imagine a white on a colored background and black or RGB full blue on white background. I will adjust our hex and run every submitted color through the tester so that we can ensure no contrast issues. We are waiting on orgs to submit their colors, will get the list asap.

**Comment by stacietaylorcima** [comment]
Hey @alavatelliMCA! Have the other organizations submitted their colors yet?

**Comment by alavatelliMCA** [comment]
I have 1, and we have a new one for ourselves since we failed the contrast test. I loved the pink, but we'll have to part ways.
Updated:
MCA: #0000FF (blue)
Smart Museum: #ee3224 (red)

**Comment by stacietaylorcima** [comment]
Hi @alavatelliMCA ! A couple things here: 

The blue (#0000FF) you sent over meets accessibility requirements with small white text (8.59), but not small black text (2.44 ratio). This is only an issue in one spot on the game: the "end game" link on the left side of the footer. We have 2 options here: 

1. **Keep the blue you chose, but make the "end game" link white instead of the black** portrayed on the design guide. I like this option best because it is going to be easier for organizations to choose a color that they like. With this solution, they will only need to ensure the background color has a contrast ratio of >4.5 against a white small text (not white and black). I also like this solution because I haven't implemented the black "end game" yet and wouldn't have to change anything except the organization's color. Haha! 

_Image of the Scavenger Hunt design guides that points to the black end game on color background._ 
![end game white](https://user-images.githubusercontent.com/25017973/46116989-a537bb80-c1b3-11e8-97e9-c61f38737216.png)


2. **Choose a color that is accessible with both small black and small white text.** Here is a blue that would work: #6161FF. It has both a contrast ratio of more than 4.5 against white small text and black small text.  

_Screenshot of the color analyzer showing a blue that scores 4.5 against white small text and 4. Against small black text._  

![screen shot 2018-09-26 at 5 44 15 pm](https://user-images.githubusercontent.com/25017973/46117033-d44e2d00-c1b3-11e8-8229-4c7f918371a5.png)

I suspect you already have a color contrast analyzer of choice, but I thought I'd send the one I've been using: https://webaim.org/resources/contrastchecker/. If we go with option #1, your process seems to be on-point with ensuring color contrast of more than 4.5 with white foreground. If we go with option #2, we'll have to ensure contrast of more than 4.5 with a white AND black foreground. Let me know what you'd prefer. Thanks a million! :-)

**Comment by alavatelliMCA** [comment]
Hey hey! Great news, pink is back!

Just realized that it passes, because the entire interface operates on large text. I'm on the phone with Sina now and he says if y'all agree after looking at this screenshot then we're good.

![screen shot 2018-09-28 at 6 40 38 pm](https://user-images.githubusercontent.com/8040710/46238049-45c1e300-c34e-11e8-9034-7bdadc3ab56d.png)

Pink hex is: #FF00FF

**Comment by sinabahram** [comment]
+1, since everything is large text, as long as we can make sure to guarantee this to be true e.g. >16PT in all places, and I mean that in normalized way since REMs don’t map to PT without going through PX first.

 

Stacie, can you make that change please in the DB?

**Comment by stacietaylorcima** [comment]
@sinabahram @alavatelliMCA Correct me if I'm not doing conversions right, but the organization name on the clue and hint view, and the footer that includes "end game", "see all clues", and the time details is all 13px which converts to 10pt. And the leaderboard is 17px, converting to 13pt. I think those elements are small text.

**Comment by alavatelliMCA** [comment]
what is the minimum for large text? I want to figure out how I can advise.

**Comment by sinabahram** [comment]
Per the below, taken from WCAG 2.1, as long as we use 18pt as our definition of large text, where it’s 18pt assuming 100% everything else, then I’m good.

 

large scale (text)

with at least 18 point or 14 point bold or font size that would yield equivalent size for Chinese, Japanese and Korean (CJK) fonts

NOTE

Fonts with extraordinarily thin strokes or unusual features and characteristics that reduce the familiarity of their letter forms are harder to read, especially at lower contrast levels.

NOTE

Font size is the size when the content is delivered. It does not include resizing that may be done by a user.

NOTE

The actual size of the character that a user sees is dependent both on the author-defined size and the user's display or user-agent settings. For many mainstream body text fonts, 14 and 18 point is roughly equivalent to 1.2 and 1.5 em or to 120% or 150% of the default size for body text (assuming that the body font is 100%), but authors would need to check this for the particular fonts in use. When fonts are defined in relative units, the actual point size is calculated by the user agent for display. The point size should be obtained from the user agent, or calculated based on font metrics as the user agent does, when evaluating this success criterion. Users who have low vision would be responsible for choosing appropriate settings.

NOTE

When using text without specifying the font size, the smallest font size used on major browsers for unspecified text would be a reasonable size to assume for the font. If a level 1 heading is rendered in 14pt bold or higher on major browsers, then it would be reasonable to assume it is large text. Relative scaling can be calculated from the default sizes in a similar fashion.

NOTE

The 18 and 14 point sizes for roman texts are taken from the minimum size for large print (14pt) and the larger standard font size (18pt). For other fonts such as CJK languages, the "equivalent" sizes would be the minimum large print size used for those languages and the next larger standard large print size.

**Comment by alavatelliMCA** [comment]
That is much larger than what I understood from the webAIM contrast checker, this is why I thought you meant 18px, it aligns with the rule on their site–
"WCAG 2 level AA requires a contrast ratio of at least 4.5:1 for normal text and 3:1 for large text. Level AAA requires a contrast ratio of at least 7:1 for normal text and 4.5:1 for large text.
Large text is defined as **14 point (typically 18.66px)** and bold or larger, or 18 point (typically 24px) or larger."

According to your numbers, we will not be able to consider the bulk of content as large text without a full redesign, so please confirm it is indeed 18 pt required. In which case, we'll go back to all the orgs (who we already pushed to get a 3:1 contrast ratio) and get new colors.

**Comment by sinabahram** [comment]
Exactly, we’re both saying the same thing.

 

“14 point (typically 18.66px) and bold or larger, or 18 point (typically 24px) or larger.”

 

So, we can have 14PT e.g. 18.66PX text, but it must also be bold; otherwise, 18PT == ~23PX before it can get away with being regular.

 

Is that the case on our pages for the scavenger hunt i.e. that the text is 14PT or there about, but bolded?

**Comment by sinabahram** [comment]
Sounds like a plan!

**Comment by stacietaylorcima** [comment]
Hi! I can totally make all the updates necessary. Just to be clear, y'all want me to go in and make all the font at least 18.6px (some of it is still at 13px & 17px) then update the MCA color back to the fabulous pink. Yes? @sinabahram @alavatelliMCA

**Comment by sinabahram** [comment]
That’s my understanding, yes.
