### ISSUE TITLE
Empty search result with large count/pagination

### ISSUE THREAD

**Issue by alavatelliMCA** [coyote-team/coyote#23]
Debug empty search result with large count and pagination

**Comment by seeReadCode** [comment]
Will add a test case...

**Comment by seeReadCode** [comment]
Ok, I am having trouble replicating this one.  Does anyone have a link for an example?

**Comment by alavatelliMCA** [comment]
I don't know what this was, @sinabahram do you remember context?

**Comment by sinabahram** [comment]
I believe that this had to deal with the fact that on a certain search, no results would come up, or pagination was there or wasn’t there, but there were no results to go through, etc. etc.

 

However, this may no longer be an issue because I think it actually was a symptom of a synchronization issue that has hence been fixed.

**Comment by seeReadCode** [comment]
I'm going to close this until we can replicate it.
