### ISSUE TITLE
Ready to Review: Approve, Edit, Reject (view becomes edit)

### ISSUE THREAD

**Issue by alavatelliMCA** [coyote-team/coyote#231]
Buttons on Ready to Review should be Edit, Approve, Reject 
Currently the options are View, Approve, Reject
![screen shot 2018-09-14 at 4 31 19 pm](https://user-images.githubusercontent.com/8040710/45576160-aecc3580-b83b-11e8-8848-d18253c6ceb4.png)

**Comment by sinabahram** [comment]
Question:

Then how do we “view” it? the thing itself being a link?

**Comment by alavatelliMCA** [comment]
It's ideal to jump straight into editing from the dashboard because if we aren't hitting the approve button we need to fix something in the description. I don't think there is a need to view the description page from this queue. 

I realized because I was on a mission approving as many as I could in current coyote, and when I returned to reviewing new coyote I noticed the difference. We almost always have at least one edit before approving.

**Comment by sinabahram** [comment]
That’s understood from a workflow point of view, but does not answer my question. It needs to be possible to do the “view” action some how since that’s a screen that exists for a reason, right?

 

Do we have another way of achieving this? I just want to make sure we don’t inadvertently orphan view functionality, regardless of whether or not it is used a lot.

 

Hope that makes sense.

**Comment by alavatelliMCA** [comment]
View appears all over in many other contexts, this change would just be to the ready to review queue.

Anna Chiaretta Lavatelli
Director of Digital Media

Museum of Contemporary Art Chicago
220 E Chicago Ave
Chicago, IL 60611
alavatelli@mcachicago.org<mailto:alavatelli@mcachicago.org>
312-397-4047<tel:312-397-4047>
mcachicago.org<http://www.mcachicago.org>
This message is for the designated recipient only and may contain privileged,
proprietary, or otherwise private information. If you have received it in error,
please notify the sender immediately and delete the original. Any other use of
the email by you is prohibited.

**Comment by sinabahram** [comment]
That’s super fair. Ok, thanks for that.

**Comment by flipsasser** [comment]
@stacietaylorcima okay here's what I saw: the conditional `if defined?(form)` returns `false` in this context, because we are not in a mass-editing scenario; instead, we are providing quick contextual links to the admin users. So I moved the "Edit" link above that conditional to ensure it's always rendered, which seems to work for me.

Take a peek here: https://github.com/coyote-team/coyote/pull/322

**Comment by stacietaylorcima** [comment]
Closed by PR #322
