### ISSUE TITLE
Audit log updates (3)

### ISSUE THREAD

**Issue by alavatelliMCA** [coyote-team/coyote#234]
I just updated Leah's description of this to test–https://staging.coyote.pics/representations/5768
3 issues occurred:
- my user is not tracked as having made the change, my changes are attributed to **unknown**
- the status label changes to **approved** everywhere and should still be **ready to review** on the previous lines (when first created and when updated)
- a `["` appears on either side of the description entry

Two columns display `[nil, ""]` as opposed to being blank
https://staging.coyote.pics/representations/3246

**Comment by stacietaylorcima** [comment]
Ok, so there are 4 items to fix here and these are my thoughts/questions: 

**Get rid of the brackets:** Audited returns the previous and updated values as an array. We need to take that array and run `.join(", ")` on it.  We could potentially do this using a helper method on each `td`. However, it gets a little weird when you update an attribute that originally had no value. For example: If there was no content_uri when the resource was created, that field would be empty. Then, when you update it to be `https://www.example.com`. You'd see: ` , https://www.example.com`. **So, my question is: Do we want to move forward with applying a helper and removing all the brackets? Or do we want to just keep them how they come from Audited?** 

**Some columns display [nil, ""] as opposed to being blank:** I fixed this in PR #282. To fix this, we needed to set the default value of all text field attributes to "" instead of nil, because what is happening is that Audited is reporting all updates in the audit log and when we set the default to nil, the user clicks save on their edit form and blank text fields are submitted. Therefore, Audited says: this field was updated from nil to "". On our audits table, we need to set the starting value of any text fields to "". That being said, when a new value is originally set, you will still see ["", "https://www.example.com/"] because it is showing that the value used to be: empty string. Now it is: whatever the updated value is. However, it won't capture a change from nil to "".

**Status labels only reflect current value:** This was my mistake! A while back, I was fixing some style issues on the audit log (displaying the tag style for values on the audit table), but to be honest, didn't understand the Audited library - or even know what it was and how it displayed. Anyway, I know more now and see that the tag styles I was applying didn't work with Audited. So PR #282 is basically restoring functionality so that the audit log shows the previous value and the updated value. I'll have to open a new issue and go back to style them like tags later on. **So, this is fixed, but it's back to being not pretty.** 

**User Not Being Tracked:** The problem seems to be that the user who updated the representation is nver getting stored and is always defaulting to "Unknown". I've been digging into the Audited docs and just can't figure out how the user who updated the representation is supposed to be mapped to the Audited username attribute. **I may need someone else to take a look at this or troubleshoot with me.** 

**So 2 asks here:** 

1. Are we sure we want to get rid of the brackets and if so, is building a helper method and applying it the best solution? 

2. Can someone take a look at how username is supposed to map to Audited? Or wanna walk through it with me? 

@sinabahram @flipsasser

**Comment by alavatelliMCA** [comment]
On staging it seems like many of the fields are missing from the audit log as shown in screenshot of this page: https://staging.coyote.pics/representations/6160

![screencapture-staging-coyote-pics-representations-6160-2018-10-03-12_36_23](https://user-images.githubusercontent.com/8040710/46428192-f6423500-c708-11e8-8212-63bb893d56d8.png)

**Comment by flipsasser** [comment]
@stacietaylorcima 1. yes, a helper method would be great. Possibly even have it do something like

```
def audit_change_to_text(change)
  old, new = change
  if old.blank?
    %("#{new}")
  else
    %("#{old}" → "#{new}")
  end
end
```

^ pseudo code I haven't tested, but the idea is to represent the change in an easily-consumed manner

2. I'm looking into this!

**Comment by flipsasser** [comment]
@alavatelliMCA @stacietaylorcima @sinabahram it appears that audits only track what changed, and not the full state of the object at the time (as that is inferable).

I'd recommend we shift this from being a grid table to a list of relevant changes. Otherwise, the vast majority of use cases (updating one column, as in `text` or `status`) will wind up with a swath of blank columns.

**Comment by sinabahram** [comment]
I completely agree with this approach, but we’ll need @alavatelliMCA to confirm

**Comment by alavatelliMCA** [comment]
Sounds good to me. As long as everything is tracked. It seems that much data is not there at all, e.g. status.

**Comment by sinabahram** [comment]
Anna, I think it’s super important to be exact when we are saying that data is missing. I don’t know of a single piece of data that is currently missing.

 

What’s happening here is that if status didn’t get changed but something else did 5 times, then you will have 5 empty squares of status, but that’s because it never got changed, so there’s nothing to report. Audit only reports the difference. That’s why the grid is such a bad idea here. the alternative is to keep the grid, but fill everything in with the values, which can be inferred, but that seems like far more content just to indicate “hey, status changed”

 

so, if the above is your understanding as well, and you are still saying that lots of data is missing, can you please provide exact examples of that missing data so we can hit that hard? To my understanding so far, we’ve established a UI issue, but not that any data, what-so-ever, is missing. It’s fine if it is … we can fix it, track down the bug, etc., but I just wish to be super clear so we know what we’re trying to do and needing to fix.

 

I hope that makes sense.

**Comment by alavatelliMCA** [comment]
I understand, but what I am saying is that if the data is not displayed then I don't know if it exists. 

Even if only at the moment of creation I think that key information– author and status–should be displayed. Currently, the audit log doesn't show any information at all besides user, date, action, and description–no author or status change info, for instance, is displayed (none of the fields past description contain content in the screenshot).

**Comment by alavatelliMCA** [comment]
Hi all, to clarify. When viewing this description and looking at the audit log there are three things

1. What did Susan do? I see several updates, but no information
2. We only need to display updated description (not before and after) when changes are made, since the previous version is displayed in the creation line
3. the narrow column on the description field (adjusting is a nice to have) feel free to reformat 
–this is a low priority item for now

https://staging.coyote.pics/representations/6108

![screencapture-staging-coyote-pics-representations-6108-2018-10-04-09_57_13](https://user-images.githubusercontent.com/8040710/46482805-eafc1180-c7bb-11e8-8f6a-f53176884df9.png)

**Comment by stacietaylorcima** [comment]
@alavatelliMCA I feel like I remember you saying at one point that you'd prefer the audit log only display the newly changed values instead of a comparison, but I can't find it anywhere. Do you want the old and the new values displayed like this: en → sp. OR, would you prefer just the updated value display in each audit?

**Comment by stacietaylorcima** [comment]
@flip I updated the audit log to be a list-like table. I removed the quotes and brackets on the audited values and replaced the comma with an arrow to make it more readable. I made it so that each audit only show's rows for info that was actually updated. The exception to this is that I have it showing the username, action, and time on every audit because those details seem important. I also added the number of audits for each representation on the view (that seemed helpful). 

@flipsasser I have a few questions for you: 
1. I need to somehow say: if the audit is the first audit (which will be the audit that was created when the instance was created), show %(#{old}). I stuck in an `elsif the new value is blank`, to show `%(#{old})`, which made the creation audit look perfect, but it's not a good option because it doesn't account for when a user removes the representation's notes for example. Do you have thoughts on the best way to do this?
2. The following fields were displaying the incorrect details: Author, Endpoint, License, Metum. I think it has something to do with the fact that all these fields were trying to use the audited attribute (which generally reflects an id) to find that object's name/title. So, for example, when the endpoint is updated, Audited notes that the `endpoint_id` is changed from 2 to 6. But, if you try to apply this logic: `Endpoint.find_by(id: endpoint_id)&.name` it only shows the previous value. I need to figure out how to get the names of both those attributes in the view. Any ideas?
3. I still am not getting the username to work right. It's clear that it was working at some point in time because Anna's screenshots show different users making changes on the audit log, but I can't figure it out. Did you ever have a chance to look into this part? 

Here is the commit with all the new code and some comments mentioning what I touched on above: https://github.com/coyote-team/coyote/commit/ae3c11f68fbcb7eaa0c91e6d681b950504aca386

**Comment by flipsasser** [comment]
The audit logs were totally revamped in June and this is no longer an issue
