### ISSUE TITLE
Functionality: After returning to clue starts hint sequence to first hint

### ISSUE THREAD

**Issue by alavatelliMCA** [coyote-team/coyote#242]
From each hint page when you "return to clue" and you decide you still need another hint you are sent back to the first hint no matter how many you have viewed.

**Comment by stacietaylorcima** [comment]
I wanted to get some more thoughts on this issue. Sina and I were chatting and thought that perhaps a `session` variable was being stored at the hint level that actually needed to be at the clue level so that it would pick up if a user has already view hints on that clue. But I can't find a sessions variable. It very well might be there I just am looking for the wrong things. This is again something that is very simple, but I can't totally wrap my head around. 

Every time the user clicks "I need a hint" from the clue's show view, they run the `first_hint` method. I'm wondering if can we just modify the `first_hint` method to say something like: serve hints in the order of ordinality starting with hints where `used_at == nil` and if no `used_at == nil` serve the hints by `used_at` ascending order. Is this totally off-base? Are there any other solutions that would work better? 

@sinabahram

**Comment by stacietaylorcima** [comment]
@flipsasser Since you're really familiar with the Scavenger Hunt, do you have any thoughts on my message above? Or how to best implement this?

**Comment by stacietaylorcima** [comment]
Hey @flipsasser! As @sinabahram and I were going over this issue, we noticed there is no “previous hint” mechanism like there is in the designs. The show hints path does not remember the hints that a user has already been shown. All the logic that would be implemented in building that feature should solve this issue here. Can you build that feature?
