### ISSUE TITLE
Answer variations acceptance needs solve

### ISSUE THREAD

**Issue by alavatelliMCA** [coyote-team/coyote#243]
We have a correct answer of "10", but "Ten" is not accepted.

**Comment by sinabahram** [comment]
Stacie, I think you’re getting  a bit lost in the details, so let’s zoom out for a second, and then solve the problem.

 

Note, I dislike the idea of accepting “ten” when “10” was the answer provided in the CMS. It’s black magic of the highest order, incredibly unclear, not at all intuitive, and most definitely not default behavior, IMHO. Having said all that, as a technical programming problem, it is quite easy to solve, so let’s go through that before making a decision on whether or not to do it or force answers to reflect this intent instead by asking for “ten” and “10” in the CMS.

 

So, what do we want to do? We want to equate the following:

 

10 and ‘10’ and ‘ten’ and ‘Ten’ and ‘TEN’ …..

 

What are we given? Let’s assume we are given ‘10’ because the CMS accepts strings.

 

We can trivially convert ‘10’ to 10 by simply to to_i(). So now we can equate ‘10’ and 10.

 

We further can convert everything to lower case with to_lower() so that takes care of ‘ten’, ‘TEN’, ‘Ten’, and so forth.

 

Now the question is simply how we go from 10 to ‘ten’

 

There are a myriad of ways to do this. humanize does this and so does the to_words gem.

 

Note, sometimes these gems do the following conversion:

‘101’ ==> ‘one hundred and one’. That makes humans who incorrectly pronounce numbers happy, but it’s not accurate. The convention of saying and at the end of numbers is ridiculous and incredibly unscientific/ambiguous, IMHO. ‘and’ should be used for fractional components ‘one and one half’ for example is 1.5, but ‘one hundred and 5’ I claim is meaningless. Yes, we all do this, but we’re not writing a speech recognition service here where we must account for spoken convention, and luckily for us we’re hopefully not dealing with numbers larger than 10, but I’ve proposed a solution below to both concerns.

 

The following simple function was taken from the top StackOverflow answer on this page:

https://stackoverflow.com/questions/19445003/using-ruby-convert-numbers-to-words

 

def in_words(int)

  numbers_to_name = {

      1000000 => "million",

      1000 => "thousand",

      100 => "hundred",

      90 => "ninety",

      80 => "eighty",

      70 => "seventy",

      60 => "sixty",

      50 => "fifty",

      40 => "forty",

      30 => "thirty",

      20 => "twenty",

      19=>"nineteen",

      18=>"eighteen",

      17=>"seventeen", 

      16=>"sixteen",

      15=>"fifteen",

      14=>"fourteen",

      13=>"thirteen",              

      12=>"twelve",

      11 => "eleven",

      10 => "ten",

      9 => "nine",

      8 => "eight",

      7 => "seven",

      6 => "six",

      5 => "five",

      4 => "four",

      3 => "three",

      2 => "two",

      1 => "one"

    }

  str = ""

  numbers_to_name.each do |num, name|

    if int == 0

      return str

    elsif int.to_s.length == 1 && int/num > 0

      return str + "#{name}"      

    elsif int < 100 && int/num > 0

      return str + "#{name}" if int%num == 0

      return str + "#{name} " + in_words(int%num)

    elsif int/num > 0

      return str + in_words(int/num) + " #{name} " + in_words(int%num)

    end

  end

end

 

as you can see above, it’s super straight forward to build a string representation of these numbers because English number names are compositional e.g. if ‘17’ appears in a 500-digit number, we still use the word seventeen. I would also replace dashes with spaces just so if someone types ‘one-hundred’, it gets treated as ‘one hundred’, which from the above will equate to 100.

 

So, the simple heuristic is:

 

#1: get answer from CMS and convert to an int with to_i

 

#2: try to_i on answer from user. If successful, then simply compare against int from #1.

 

#3: If to_i fails because they typed words, then simply compare the lower case, dashes replaced with spaces, version of the answer from the user against the return from in_words() being run with the int from #1 as its argument.

 

That’s it. you’ve now got a way of equating ‘ten’, ‘tEn’, ‘Ten’, 10, ‘10’, etc.

 

Ok, now that we’ve got the technical solution out of the way, we should discuss whether this is a good idea. The reason I don’t summarily reject this as the wrong thing to do is because we don’t offer an affordance to the user e.g. bringing up only a number pad entry field, restricting input to just digits, etc. etc.

 

As a result, it is “our” responsibility as the scavenger hunt to tell the user how we expect them to convey to us the concept of ‘10’, and so I get the request and the reasoning/justification for it. it’s also beneficial to those with cognitive impairments or print processing disorders like dyscalculia to be able to express numbers with words.

 

It is because of those reasons that I’m ok with this, but in a more mature product, I would want this behavior to be controlled by a setting or other editor-controllable flag, you know?

 

So, let’s proceed to accept all the variations of ‘10’ in word form. feel free to use the solution above or something else, but you get the approach, I trust?

 

Also, if I didn’t explain anything sufficiently or if the above is in any way unclear, that’s on me, and please ask follow-ups galore.

**Comment by stacietaylorcima** [comment]
THIS is amazing info. I'm putting it to work right now! I'll let you know if I have other questions. Thank you so much for all this detail.
