### ISSUE TITLE
Unassign User on Representation Rejection

### ISSUE THREAD

**Issue by alavatelliMCA** [coyote-team/coyote#246]
The action REJECT, unassigns the user who wrote description and puts the resource back into the unassigned queue if not assigned to anyone else.

**Comment by stacietaylorcima** [comment]
@alavatelliMCA Quick questions so that I can better understand the process here: Is the idea here that a resource will only ever be assigned to one user? Does being assigned a resource mean that the user is supposed to go in and create a description or does it mean that user is responsible for going in and approving/rejecting all existing descriptions?

**Comment by stacietaylorcima** [comment]
@flipsasser @sinabahram I racked my brain over this for a while and wanted to get your thoughts/guidance before spending any more time potentially going in the wrong direction.

My thoughts were that this logic might be used in the represenations_controller update method, since that is what is being called when a user rejects a representation. (Although, it should probably actually live in maybe the representations_helper and just be called in the update method.)

```
  def update
    if representation.update(representation_params)
      logger.info "Updated #{representation}"


      # this is sort of a pseudo code version of the conditional that would live in a helper method 
      if representation.status == "not approved" && representation.author has no other representations on that resource
       DELETE FROM assignments WHERE assignment.resource_id = representation.resource_id && representation.author_id == assignemnt.user_id
      end


      redirect_to representation_path(representation), notice: 'The description has been updated'
    else
      logger.warn "Unable to update description due to '#{representation.error_sentence}'"
      render :edit
    end
  end
```

Do you think this idea is on target? Do you think it is totally whack? Have any suggestions?

**Comment by stacietaylorcima** [comment]
These were comments in Slack from Sina that I wanted to put here for reference as well: 

I think flip should respond but I just wanted to say from a logical perspective, we should only unassign the resource from the user if they are not in the process of authoring any other representations for that resource. In terms of how the system thinks about it, after a representation is approved, is the resource still assigned to the person but with some sort of completed status? If so, then this needs to be managed very carefully. On the other hand, if it really does work like a queue and assignments are removed when the resulting representations are approved. Then the only thing to check is any other unapproved representations by that user.

cc @flipsasser

**Comment by stacietaylorcima** [comment]
@flipsasser Can you give any insight on how you think this should be implemented?

**Comment by flipsasser** [comment]
@stacietaylorcima your deletion logic is sound, but this belongs in the model itself as part of an `after_update` hook. It should look something like:

`after_update :unassign_user, if: -> { status_changed? && not_approved? }`

**Comment by flipsasser** [comment]
This is on staging
