### ISSUE TITLE
Date discrepancies in Coyote data

### ISSUE THREAD

**Issue by alavatelliMCA** [coyote-team/coyote#271]
I searched on records added on 8/30 (the day we did the dump) because I thought it was weird that last image in the list was in June (I had recalled that being a July image), and I found a major discrepancy:
https://staging.coyote.pics/resources/20051
On new coyote this image shows as being created 2018-04-23 22:42:11 UTC
https://coyote.mcachicago.org/images/21175
On old coyote it shows as being created 2018-08-30 22:01:53 UTC (which is correct)

**Comment by sinabahram** [comment]
I have a suspicion that it is just using time of import instead of copying over the timestamp from old Coyote.

 

Hopefully, while absolutely critical, this is a very easy fix.

**Comment by sinabahram** [comment]
The more I think about this, the more I disagree with my previous assertion. Something else is going on here.

**Comment by alavatelliMCA** [comment]
Let me know when to review details of the content sync again.

**Comment by sinabahram** [comment]
Please proceed. The new data has been up for four days now. I was under the impression that this process was well underway. The new data was uploaded to live/production and since staging has been updated since then, it will have trickled to staging as well.

 

The time issues should be resolved, according to @FlipSasser, and the priority issue turned out not to be a thing since in fact priority was all 0/off on old Coyote when you checked.

 

Here’s to hoping there are no other data issues!

**Comment by flipsasser** [comment]
Marking this as fixed!

**Comment by alavatelliMCA** [comment]
https://coyote.mcachicago.org/images/20089

https://live.coyote.pics/resources/20089

Thank you, yes, this appears to be resolved.

Although, I think that on one version time is labeled as UTC but it isn't since all the dates are correct but are 7 hours earlier in new coyote. Perhaps new coyote is actually East Coast Standard Time? Not too worried about this, but would be good to know at some point.
