### ISSUE TITLE
Leaderboard content approach

### ISSUE THREAD

**Issue by alavatelliMCA** [coyote-team/coyote#275]
Notes on how the leaderboard SHOULD operate:

The leaderboard should get archived and then wiped out everytime content is changed.

How do we handle this for launch? 
- Leaderboard expires when we launch, we post winners on the website (and full leaderboard?)
- When content for an organization changes, their leaderboard wipes out. 
concerns:
- How do we know when to archive leaderboard before it gets wiped out?

**Comment by sinabahram** [comment]
Note to devs:

Most of these topics are tabled until after launch.

 

The one critical thing that must be figured out right now is simply that we can clear the board upon launch to make sure we start with a blank slate. The board will then not be cleared until we establish answers to the issues highlighted in this ticket e.g. automatic clearing, archiving, etc. are all issues for future development pending additional resources.

 

The one critical assumption to verify is that boards are scoped per organization.

 

@FlipSasser can you please confirm the assumption and the ability to clear of the issue pre-launch above?

**Comment by flipsasser** [comment]
In the UI, the leaderboard is not scoped to organization but I have a pull request up to make that happen.

Otherwise, yes we can easily clear out before launch.

Can you please confirm that the preferred behavior is that when **any** game content changes (e.g. anyone adds, deletes, or updates representations that make up the game), we should clear the leaderboard? Or should we only be clearing it for certain meta, e.g. when a questions are modified but not position?

**Comment by sinabahram** [comment]
Answers inline:

 

FS:

In the UI, the leaderboard is not scoped to organization but I have a pull request up to make that happen.

 

SB:

wonderful and thank you!

 

FS:

Otherwise, yes we can easily clear out before launch.

 

SB:

Thanks again

 

FS:

Can you please confirm that the preferred behavior is that when any game content changes (e.g. anyone adds, deletes, or updates representations that make up the game), we should clear the leaderboard? Or should we only be clearing it for certain meta, e.g. when a questions are modified but not position?

 

SB:

Technically, only when questions/answers/hints are modified but not things like position. This has to do with expediency and level of effort, though. what can be fully completed today, without needing to spend time on this next week, etc.? for example, if invalidating based on content changes is possible, then we have to discuss what that means e.g. are they archived, per Ann’as request (this takes far more building out IMHO), or simply discarded, or at least captured in an email for posterity, etc.?

 

So, Flip, back to you. what’s possible to get done and fully completed with a minimal level of effort today, realizing that there are some data migration and permissions stuff that are more important for you to look at?

 

Thanks for the thoughtful answer on this!

**Comment by flipsasser** [comment]
Hue hue hue, I wrote that response before I created the pull request. My intention was to click "comment" once I'd put it up, but then in my zeal to act, I clicked "Comment" anyway. Anyhoo... it's up now.

Re: wrapping up the auto-creation of locations, I'm working on that now. I'll default to the blue color that you and Stacie mentioned (and that's on staging currently). We can always go in and update locations' colors manually as-needed, after the fact.

**Comment by flipsasser** [comment]
Okay, there's a PR up that creates locations and meta as organizations are created, and archives games from the leaderboard whenever resources with representations with game meta, or representations with game meta, are created, updated or destroyed!

**Comment by sinabahram** [comment]
Just one important thing.

 

You said:

created, updated or destroyed

 

but shouldn’t it be?

Approved ones are updated or destroyed

 

Just creating a question for possible later content, etc. should not invalidate the current game, and doing anything to unapproved resources also shouldn’t, right?

 

Other than that, this seems amazing.

**Comment by flipsasser** [comment]
Updated to reflect only approved representations. Changes to resources with approve representations also archive games, e.g. if the source url or title changes, the games are archived. Please advise if that works!

**Comment by sinabahram** [comment]
That makes perfect sense to me.

 

When they are archived, what exactly happens to them?

 

Is it just a flag to let us know not to display? Is there a list? just wondering.

**Comment by flipsasser** [comment]
We are archiving games, so I'm going to close this!
