### ISSUE TITLE
Scavenger hunt text edits - editorial review

### ISSUE THREAD

**Issue by susanchun** [coyote-team/coyote#292]
Hi @stacietaylorcima! Here are the text edits consolidated. Please let me know if you have any questions. The email I sent earlier today shows the changes in red, you may want to consult it if you have any questions, but cutting and pasting from this list should work as long as you don't truncate or eliminate anything. We are working to consolidate all design notes into a separate doc as there are a number of spacing and sizing issues, most of them consistent style changes. 

<INTRO>

_Play at cultural spaces throughout Chicago. The game is a time trial. You cannot save your progress: end the game at any time to submit your score._

How the game works:
 
_2 Use clues (descriptions) to find works_ 
 
<WHERE ARE YOU?>
 
_Delete "Choose your location"_
 
<x of x Clues Completed>
 
_Missing COYOTE link in upper left_
 
<SUBMIT YOUR SCORE>
 
_Submit your score_
 
_Your email is required to win a prize. We will only contact you if you are a winner. Only your username is displayed on the leaderboard._
 
<Form entry>

_Username (required)_
 
<THANKS FOR PLAYING>
 
_Tell your friends about the game. #playcoyote_
 
_Watch for new clues and game days at coyote.pics/hunt._
 
_Did you know that Coyote Scavenger Hunt uses descriptions that were created to help visitors who are blind or have low vision enjoy artworks and cultural objects? Learn more at coyote.pics._
 
<LEADERBOARD>
 
_Click to see scores by location._
 
<SURVEY>
 
_Your responses will help us improve the game._
 
_Would you play it again?_
 
_What would you change?_

**Comment by alavatelliMCA** [comment]
Hi all, I am reopening because a couple edits slipped through the cracks and with text updates there are a couple other typos. I am checking on staging for the record. Changed items are in bold

[ ] need semicolon after How the game works**:** on the welcome page
[ ] need period **.** after sentence **There are 5 clues at this location.** for all location landing pages
[ ] Submit your score page "When you submit your score you end your game at all site**s**.
[ ] Submit and view the leaderboard should be left aligned

**Comment by stacietaylorcima** [comment]
I made all but the last update just now and have to run til tonight! I'll get to the last one though! @alavatelliMCA
