### ISSUE TITLE
Hint style adjustments

### ISSUE THREAD

**Issue by alavatelliMCA** [coyote-team/coyote#302]
Default all hint text should match H1, size, same as the "are you sure you want this hint?" on the page before.

Order of nav options (top-bottom, left-right)
- I found it
- Return to clue
- Next hint
- Previous hint

Reduce scale of “Clue 1/2” to match location/end game/etc. sizes

**Comment by stacietaylorcima** [comment]
@flipsasser I'm having trouble adjusting the line height here on the hint text (`  = representation_content @hint.representation`). I can adjust line-height successfully from the console, but I'm running into issues since `representation_content` sends the representation to `representation_text` which returns it as a `p`. I can apply `h1` to it, but it makes the line height all wonky, I believe because of the `p`. Anyway, do you have any thoughts on how to get around this? 
![line height adjustment](https://user-images.githubusercontent.com/25017973/46376626-4e1a6680-c64b-11e8-9d48-7aa0505c3aa6.png)
