### ISSUE TITLE
Thanks for playing! page adjustments

### ISSUE THREAD

**Issue by alavatelliMCA** [coyote-team/coyote#306]
- Start Over should be only element fixed on bottom menu, all other items should descend from top
- Default Leaderboard and Survey options should match H1 scale/style

**Comment by susanchun** [comment]
Adding to this: Can we change #playcoyote to #PlayCoyote per Sina's note from yesterday (sorry, just digging out now).

**Comment by alavatelliMCA** [comment]
Also, for this thanks for playing page, the links for View Leaderboard and Take Survey should be part of the page not locked to bottom of frame, only Start over should be bottom of page locked.

**Comment by stacietaylorcima** [comment]
@alavatelliMCA When you say, "Default Leaderboard and Survey options should match H1 scale/style" do you mean the links for "view the leaderboard" and "take the survey"?

**Comment by sinabahram** [comment]
@alavatelliMCA, friendly poke

**Comment by susanchun** [comment]
Hi Stacie, Gabe here, writing from Susan's account.

Correct. The 'View the leaderboard' and 'take the survey' links should be inline with the other content in the body of the page, rather than being fixed to the bottom nav.

Looking at the page currently, it is absolutely appropriate for those two links to match type styles with the h3 p text currently set above.

Does this clarify?

![screen shot 2018-10-04 at 1 08 57 pm](https://user-images.githubusercontent.com/639747/46493891-17715700-c7d7-11e8-9fb8-55a247dcd1a8.png)

G

**Comment by stacietaylorcima** [comment]
@susanchun Hi Gabe! Yes, that's what I was asking about. I asked because I made them h1 like suggested in the original comment of this issue and that looked really weird. So, I'm glad you said h3. I'll update them!
