### ISSUE TITLE
Survey text input field focus state adjustment

### ISSUE THREAD

**Issue by susanchun** [coyote-team/coyote#332]
Hi Stacie, Gabe here, writing from Susan's accoun

There are some issues with the underline/drop shadow and spacing of the text input areas. I'll post two comments with specifics and screenshots. 

G

**Comment by susanchun** [comment]
First issue: Survey page. The text input box is very large, and the spacing is off. 

1. The "Enter answer here" should float on the line delineating the input box. 
2. Can we have the height of the box be a single line height rather than what looks like 3 or 4?
3. Top of the entry box itself, not the "Enter answer here" text, should be spaced from the question to match the spacing of the other questions and answers.
 
![screen shot 2018-10-04 at 1 59 52 pm](https://user-images.githubusercontent.com/639747/46496487-c9ac1d00-c7dd-11e8-86f3-0e37813e840a.png)


G

**Comment by susanchun** [comment]
Second issue (I can't post screenshot because the staging site has changed and I can get to the page).  

On the "Found it" page, the underline delineating the answer entry field appears to be curving up slightly at either end. Can we eliminate this effect?

G

**Comment by susanchun** [comment]
Also, can we eliminate the drop shadow around all live entry fields?

G

**Comment by alavatelliMCA** [comment]
Gabe the drop shadow is an accessibility requirement, I think it would be great to at some point talk about focus states with Sina as traditionally they are an unatractive feature and I don't think that needs to be the case. I in fact wonder if focus states could be a solid 2px outline on fields at times. In anycase to avoid confusion let's filter additional design requests through me in case of conflict.

This ticket is for the survey page: check focus state relationship to text, to avoid overlap. And underlines to avoid curved edges.

**Comment by sinabahram** [comment]
Traditionally, I’ve had clients solve this problem with a 2PX as default, and then when keypress is detected, the focus state becomes more pronounced. This way, mouse users don’t have to deal with the focus states being too large but keyboard users are not excluded by an insufficient focus state.

**Comment by stacietaylorcima** [comment]
@alavatelliMCA I was just jumping in to work on this ticket and I have fixed the spacing issue (locally) so that the text area doesn't overlap with the question. But, I'm not totally sure what you and Gabe mean when you say the underline on the text fields is curving up. I might just be misunderstanding though. When you get a chance, can you take a screenshot and point an arrow to it so I can see what you're seeing and need fixed? Thanks a million!

**Comment by stacietaylorcima** [comment]
@alavatelliMCA I was just jumping in to work on this ticket and I have fixed the spacing issue (locally) so that the text area doesn't overlap with the question. But, I'm not totally sure what you and Gabe mean when you say the underline on the text fields is curving up. I might just be misunderstanding though. When you get a chance, can you take a screenshot and point an arrow to it so I can see what you're seeing and need fixed? Thanks a million!

**Comment by stacietaylorcima** [comment]
@alavatelliMCA I was just jumping in to work on this ticket and I have fixed the spacing issue (locally) so that the text area doesn't overlap with the question. But, I'm not totally sure what you and Gabe mean when you say the underline on the text fields is curving up. I might just be misunderstanding though. When you get a chance, can you take a screenshot and point an arrow to it so I can see what you're seeing and need fixed? Thanks a million!

**Comment by stacietaylorcima** [comment]
@alavatelliMCA I was just jumping in to work on this ticket and I have fixed the spacing issue (locally) so that the text area doesn't overlap with the question. But, I'm not totally sure what you and Gabe mean when you say the underline on the text fields is curving up. I might just be misunderstanding though. When you get a chance, can you take a screenshot and point an arrow to it so I can see what you're seeing and need fixed? Thanks a million!
