### ISSUE TITLE
Update survey (no option) conditional to output label for id

### ISSUE THREAD

**Issue by stacietaylorcima** [coyote-team/coyote#341]
Check for new: `<label for="id-of-txt-area">What would you change?</label>`

**Comment by stacietaylorcima** [comment]
@sinabahram Is this what we're looking for here or am I still missing something in this source code? 
```
</div><label class="sr-only" for="answers[4]"></label>What would you change about the game?<textarea name="answers[4]" id="answers_4" placeholder="Enter answer here" rows="5">
```

**Comment by sinabahram** [comment]
A few thing:

 

1: why are you including a closing div tag when no opening one is mentioned?

 

2: the text needs to be inside the label; otherwise, you have just made an empty label. If you find yourself making empty html tags, that’s usually a sign something is wrong. Note, the textarea is a prominent exception to this rule as you can see below.

 

3: As a result of #2, take the sr-only off of the label. We didn’t discuss putting that class on there, and that’s for a good reason, since then only screen reader users would see it.

 

#4: You are incorrectly referencing the name attribute, not the ID attribute in the label. You can tell because the ID of the textarea has an underscore but the name of the textarea has brackets.

 

So, the markup, should be exactly what we talked about on the phone:

 

<label for="answers_4">

What would you change about the game?

</label>

<textarea name="answers[4]" id="answers_4" placeholder="Enter answer here" rows="5">

</textarea>

 

Note, you may need to put a class on the label. Definitely not sr-only as discussed, but rather whatever you need to make the label look correct font-wise, etc.

**Comment by stacietaylorcima** [comment]
@sinabahram Got it. Here's the new markup that matches yours above. 

<label for="answers_4">
What would you change about the game?
</label>
<textarea name="answers[4]" id="answers_4" placeholder="Enter answer here" rows="5">
