### ISSUE TITLE
Formatting for Hint footer menu

### ISSUE THREAD

**Issue by susanchun** [coyote-team/coyote#343]
Gabe here. 

For clarity, we need to address the Hint page options (I found it!, Next Hint, etc) at the bottom. 

1. All options should keep their position. 
2. Let's change the size of "Return to Clue" to 18px and position it always at the bottom left. 

I've attached 2 screenshots showing the positions and states of the lower menu. Keep in mind that type formatting is inconsistent with the live site, as I'm working this up in Indesign.

State 1 (without Previous hint): 
![screen shot 2018-10-04 at 4 43 32 pm](https://user-images.githubusercontent.com/639747/46504979-35e64b00-c7f5-11e8-9b98-1c91cc2e351d.png)

State 2 (with Previous hint):
![screen shot 2018-10-04 at 4 43 37 pm](https://user-images.githubusercontent.com/639747/46504978-35e64b00-c7f5-11e8-88bf-1787180b05cd.png)

G

**Comment by alavatelliMCA** [comment]
I'm adding to this to focus on fixing for tomorrow. Currently hint options are overlapped by the I'm done/see all clues time and clue counter.

I think this may be fixed by #375 and #376 but below is what is what we are getting:

![image from ios 1](https://user-images.githubusercontent.com/8040710/46565126-0bb68b00-c8d2-11e8-8797-6bb779585c39.png)
and
![image from ios](https://user-images.githubusercontent.com/8040710/46565128-14a75c80-c8d2-11e8-9056-fc1efdd1eac2.png)

**Comment by alavatelliMCA** [comment]
This was provided by our designer earlier to resolve hint next clue previous clue "jumping around" which was less noticeable when we couldn't actually see all the links below the footer.

![screen shot 2018-10-04 at 4 24 21 pm](https://user-images.githubusercontent.com/8040710/46567571-9a3f0280-c8fa-11e8-9e9e-47548e0c0dcc.png)
