### ISSUE TITLE
Leaderboard: Store time per location

### ISSUE THREAD

**Issue by stacietaylorcima** [coyote-team/coyote#359]
We need to store the amount of time a player spends on each scavenger hunt location. We don't need this in the view at this point, but we must be able to query because prizes are given per location.

**Comment by flipsasser** [comment]
Okay, we track all of this data currently. `created_at` on games records when a game is started at a location; `answered_at` records when each clue is answered. Games also have `ended_at` so we could either go with "latest answered_at" or "game ended_at" .

**Comment by sinabahram** [comment]
Hmm, last clue answered seems slightly unfair, because then you can try all you want on the “actual last clue you tried” but never got VS someone who just ended it honorably. So, I say “end game”

**Comment by susanchun** [comment]
But at least for tomorrow, our instructions are written to make "end game" mean AT ALL LOCATIONS, so it specifically doesn't work per location.

**Comment by sinabahram** [comment]
Hope to hop on a call to discuss, but it has always worked per-location, even since the earliest prototypes of the scavenger hunt. This has always been the case.

 

Note, this does not mean the scoreboard need be location-specific, and in fat that change has already been pushed to re-make it global, since we made it location-specific per a ticket, and then we are simply undoing that change to go back to the original plan

 

Is there a downside to this approach other than some content updates? we don’t penalize people for travel time (this is more socially fair to folks who cannot afford to Uber/Lyft all over). It’s more resilient e.g. your phone dies or something, then you don’t lose all day’s work, etc.

**Comment by flipsasser** [comment]
Closing this out as we have a way forward with #369
