### ISSUE TITLE
Feature request: resources creation / update http+json callback

### ISSUE THREAD

**Issue by jkva** [coyote-team/coyote#440]
As an API user I would like to be able to register custom callbacks to an endpoint of my choice.
An example of the payload could be:

`POST to https://myservice.com/my-callback-endpoint`
```
{
  "trigger-event": "resource_created", // or "resource_updated"
  "data" : {
    "id" : "13117"
    ...
  }
}
```

While considering header-based authorization.

Potentially this could also be in daily batches - I'll leave that up in the air for now.

**Comment by jkva** [comment]
@flipsasser I've tried out the current webhook functionality. It's a great start, yet I notice the callback doesn't fire when:

* a representation is approved
* an approved representation is modified

which is essential for me tracking updates to alternative text representations.

**Comment by jkva** [comment]
On that same note, should descriptions that have been approved be mutable? Should those not revert back to "review" when they get modified after approval?

**Comment by flipsasser** [comment]
Webhooks are now triggered by representation mutations as well as resources! Let me know if there's anything else you need

**Comment by jkva** [comment]
@flipsasser awesome! Also when a representation goes from review to approved?

**Comment by flipsasser** [comment]
Any modification on a representation will trigger the webhook, including status changes

**Comment by jkva** [comment]
@flipsasser is it possible to send an authorization token along in the request headers? I can then plugin-side verify this is a valid profile with access to the organization and approve the request.

**Comment by flipsasser** [comment]
JWT token is now coming through in request headers as `X-Coyote-Token`.

It is signed using the `token` attribute from the resource group. You can access the token via the `/api/v1/resource_groups` endpoint - it comes back when you add a `webhook_uri` or otherwise retrieve a resource group from that endpoint.

You can verify the token by generating your own copy using the HS256 algorithm, the `token` value for the resource group as the key, and payload ```json
{id: "1"}
```

where "1" is the resource's "id" provided in the request.

Let me know if you have any issues!

**Comment by flipsasser** [comment]
These are running w/JWT tokens; please open a new issue if we need changes to the token generation / verification process
