### ISSUE TITLE
Links in TOC in Readme don't work

### ISSUE THREAD

**Issue by sinabahram** [coyote-team/coyote#461]
At least for a screen reader user, using Jaws and Chrome, the API link, for example, doesn't jump me to the API ankor.

**Comment by jscholes** [comment]
Related: https://github.com/github/github/issues/135756

Will follow up on that and make sure it gets upgraded to a fully-blown spot check observation.

**Comment by flipsasser** [comment]
With the addition of the data model to the TOC, all anchor links are working

**Comment by jscholes** [comment]
@flipsasser Not for screen reader users.  This is a GitHub issue for which I'm yet to find a work-around.

**Comment by flipsasser** [comment]
AH, okay. What if I sub in full URLs for the anchors?

**Comment by flipsasser** [comment]
I tried that - can you let me know how it works, @jscholes? https://github.com/coyote-team/coyote#table-of-contents

**Comment by jscholes** [comment]
Doesn't work unfortunately.  I think the issue is that the links target headings and those headings don't have `tabindex="-1"`.

**Comment by flipsasser** [comment]
Aha! We manually add `<a name="#whatever" />` to the heading, BUT the headings themselves also add the IDs, which may short-circuit the jump. Let's try changing the links slightly.

**Comment by flipsasser** [comment]
Okay I added manual anchors to all of the headings the ToC points to. Do me a favor and try again?

**Comment by flipsasser** [comment]
Wow, Github overwrote `<a name="developer-setup-anchor"></a>` as `<a name="user-content-developer-setup-anchor"></a>` but the anchor links still point to `#developer-setup-anchor` and "works" when you click on it - which leads me to believe that yeah, there's not much I can do to prevent this thing from going haywire. I'm sorry about that!

Seems like the sort of thing they shouldn't be hacking together, since, you know... anchors have been functional without a bunch of cruft around them since the start of HTML.

**Comment by jscholes** [comment]
Exactly.  There are other issues too, such as each one acting as a permalink but the linked portion being aria-hidden.  It's on my (very) long list of things to work through with them.

**Comment by sinabahram** [comment]
Closing this because there's nothing we can do, and @jscholes  and I are handling this upstream with GitHub proper.
