### ISSUE TITLE
API feature: known alternative text on resource creation

### ISSUE THREAD

**Issue by jkva** [coyote-team/coyote#469]
When creating a new resource, I'd love to be able to provide an existing "alt text" representation. This happens in the scenario where I extract existing images from HTML and these already have alternative text defined.

**Comment by flipsasser** [comment]
@jkva @sinabahram let's discuss what to do on updates.

The logic is straightforward for creation: "we've never seen this resource -> we created it -> we also got a representation for it -> we created that"

The logic is more tricky for updates, because it's plausible that this representation was already created - or not. We could certainly say "ALWAYS create the representation if the resource has none in the given meta currently", but that still leaves the question "what if we receive alt text for a resource which previously existed and previously had alt text".

I can think of a few ways to navigate this but wanted to get a sanity check from you all first.

**Comment by sinabahram** [comment]
I think there are three options.

 

#1: We make a new meta called alt_original or something like that, and put it in there. If it already has that meta, we override its value.

 

#2: We override the alt in Coyote.

 

#3: We add another alt (there can be of course many, so nothing wrong with this in Coyote land).

 

I’m not a huge fan of #3 because it seems like then we have to figure out a multi-alt situation for things as a normal case instead of a case where we are intentionally using multiple alts e.g. in the case of alts in different languages or for different reasons.

 

#1 and #2 are kind of equal  to me. The first one offers the ability to always know/track the first original alt at the time of resource creation, which seems useful. #2 is nice and standard e.g. you had an alt for this thing, and I updated it for you, but the downside is what if someone installs the plugin, uses it, and then uninstalls it. Then they go install it again, but in the mean-time, some folks have done something silly with alt text e.g. put the word “decorative” in (I literally just saw this on a site), so then Coyote goes and overrides the alt it knows with “decorative”, and we have a lossy situation.

 

So, with all that said, my thinking is leading me to putting this in alt_original, and if there is no alt then serving alt_original so a resource doesn’t become less accessible by getting entered into Coyote.

 

Flip, if you feel the serving of alt_original if no alt is too complex/complicated/error-prone, then I vote for overriding alt.

 

Thoughts?

**Comment by flipsasser** [comment]
Just so I'm clear, when you say "alt" you mean a representation with metum "Alt", right?

If that's the case... I'd worry about #1 for exactly the reason you proposed. I'm actually fairly partial to #3, which will allow us to track changes easily.

Before we discuss this any deeper, though, I want to be sure I'm right about a few other assumptions. If you're just providing alt text:

- The author will be the user whose API key makes the request (unless otherwise specified)
- The endpoint will default to "Any" (unless otherwise specified)
- The license will default to "universal", or "cc0-1.0" (unless otherwise specified)
- The metum will default to "Short" (unless otherwise specified)
- The status will default to "not_approved" - this last one I'm extra unsure of

**Comment by sinabahram** [comment]
@flipsasser  great questions. My answers follow.

Q: The author will be the user whose API key makes the request (unless otherwise specified)

A: absolutely.

Q: The endpoint will default to "Any" (unless otherwise specified)

A: I need more info about what that means. The endpoint for a callback or some other definition of endpoint?

Q: The license will default to "universal", or "cc0-1.0" (unless otherwise specified)

A: let's use the term open access here, just so we can then postpone, if we may, whether it's CC0 or another similar license, but yes they will default open, absolutely.

Q: The metum will default to "Short" (unless otherwise specified)

A: Yes, if we accept that the general use case is short and long meta for each resource, which map to alt text for short and custom implementation for long, then absolutely short is what I mean, and you're right to point that out, as alt is simply how they are surfaced, but not the Coyote parlance for what they are.

Q: The status will default to "not_approved" - this last one I'm extra unsure of

A: This is an excellent detail. Yes, that's right, but I would like to then request that if that is true, and I think it is logical for it to be so, then the API MUST (non-optional) be A) extended to support providing this initial status on creation/upsert/whatever, and B) be forced to do so.

To recap, Flip, So I'm clear, you're saying, they come in, get mapped to short (if short exists already, override it because we have audit log), and this way if WP plugin flips the status to "approved" upon import, which I will immediatley turn around and ask @jkva  to do, then we got ourselves a transparent situation e.g. you install Coyote on WP, and all existing alts still exist as metum_short in Coyote, assuming your plugin sets status=approved on import. @jkva  We'll not only want to make this a default but an option to be set in the plugin's settings. And, allow me to shortcut another request cycle. It would be incredible if an organization on Coyote could be queried for its statuses via the API, so @jkva  knows what to put in that dropdown on his settings page e.g. "to be approved" "approved", etc.

I'm good with that.

**Comment by flipsasser** [comment]
Awesome, okay I think we're pretty close here.

I'd like to propose one more addition, then, which is that all organizations are "seeded" with default meta when they're created. This doesn't happen currently, and could lead to these assumptions not working the way we'd hoped. Reason being, if you try to create a nested representation on a resource, don't specify the metum, and we can't find a metum named "Short," it defaults to the **oldest metum the organization has.** That may seem like ... okay-ish logic, but the end result in some existing organizations would be a bunch of representations with "Scavenger Hunt: Clue" as their metum.

So I'd like to ensure some level of data integrity by generating those meta automatically when an organization is created and backfilling them on existing organizations. 

Thoughts?

**Comment by sinabahram** [comment]
First, I think that if the metum doesn’t exist, it should fail, not default to the oldest one.

 

Second, I am 100% ok with default meta of short and long, but I was also under the impression that these were the two defaults for an org.

 

We should remove scavenger from any kind of defaults.

**Comment by flipsasser** [comment]
There are no scavenger hunt defaults, but if you poke through the organizations on staging (which were imported from production), there are several that don't have Short or Long meta.

So you're saying if we can't find a "Short" metum for the organization, just reject that change?

**Comment by flipsasser** [comment]
And no they are not the defaults; when you run the database seeds in development they are created but when an organization is created, it starts with no meta.

**Comment by sinabahram** [comment]
I think it’s a simple matter of the client asking the API, put this in X, and if X doesn’t exist, that’s a failure, right? Am I missing something here?

 

I don’t think that would be reasonable with no defaults, but since we are going to provide short and long as defaults, then it means someone went in and actively changed something, so yes I am ok with them getting an error if they went in, changed meta, and then didn’t tell their WP plugin about it, for example.

 

@jkva this does mean, and this is far lower priority, that the meta the plugin specifies should be eventually able to be defined, but obviously should assume/default to short.

**Comment by flipsasser** [comment]
Makes perfect sense to me. But just to be clear - if they don't actually _specify_ meta via the API, it's okay to default to "Short" if it's available, and fail if no meta is provided and short cannot be found?

**Comment by sinabahram** [comment]
I think we should require the meta in the API call.

 

Silent defaults really concern me.

**Comment by flipsasser** [comment]
Roger dodger - which goes back to the other "defaults" I mentioned. "Endpoint" (I've never been clear on what this does) and "License" are both required, and are system-wide records rather than scoped to organization.

**Comment by sinabahram** [comment]
I have a suspicion about endpoint, but can you do me a favor and send me some values filled in for it on the system by any org? Has it been used what-so-ever?

 

I think we can remove endpoint and context eventually.

**Comment by flipsasser** [comment]
Endpoint isn't even rendered in the UI. In production, the three available endpoints are:

- Any
- Kiosk
- Website

Is this maybe what you mean by "context?" I can't find any references to context in the code.

**Comment by sinabahram** [comment]
Ahh, exactly. Context got renamed to endpoint.

 

Let’s remove that thing. We can talk over Slack about implications, but it’s not doing anything that meta can’t achieve.

**Comment by flipsasser** [comment]
You can create resources with representations using the following request body:

```json
{
  resource: {
    source_uri: "https://this.is.required/",
    representations: [
      {
        text: "This is the alt text",
        metum: "Short",
        language: "en"
      }
    ]
  }
}
```

**Comment by jkva** [comment]
@flipsasser FYI that `metum` isn't correct for `Alt`, it should be `"Alt"`. Took me a while to figure out why my batch inserts weren't working.

**Comment by flipsasser** [comment]
@jkva meta are configured at the organization level, so if the org doesn't have the short / long meta (which I believe are the default but I could be wrong), you'd need to select a different metum to specify. I guess the org you're using has one named "Alt"?

**Comment by flipsasser** [comment]
Closing this as it is apparently working as expected using the "Alt" metum on @jkva's org; open new issues if they appear!
