### ISSUE TITLE
Email members in bulk

### ISSUE THREAD

**Issue by 4-x** [coyote-team/coyote#500]
As our member list is nearing 150 users, a class of issues is developing around user management. For example, if I want to email every user, it is inconvenient to maintain a separate list of user emails and would be helpful if I could email them from the admin panel either via a `mailto` link or through the app itself.

**Comment by sinabahram** [comment]
I think that using Coyote as an email sending program is a little bit outside of the current scope of items we're concentrating on right now. Do you really have 150 active users on the platform or can most of these issues be resolved by clearing out old users, because there's only a handful of active users? Happy to discuss this more.
