### ISSUE TITLE
Log in landing page wrong organization

### ISSUE THREAD

**Issue by 4-x** [coyote-team/coyote#502]
Upon logging in, I would previously land at the top level `/organizations` page, but now I am landing on the first ordinal organization that I have access to, which is not my primary org. This is probably only an issue for users who belong to multiple orgs.

**Comment by sinabahram** [comment]
@flipsasser  when multiple orgs exist for a user, can users simply be taken to the screen to choose the org?

@4-x  as a work around for now, just bookmark the MCA Chicago Coyote org page so that you can always get there with a single click, as you should be redirected if you're ever not logged in, while this is being worked on.

**Comment by flipsasser** [comment]
@4-x which email are you logging in with, the mca-gmail one, the mcachicago one, or your personal one? Also FYI - this project being open-source means these issues are publicly visible, so please don't type your actual email out!

**Comment by flipsasser** [comment]
Follow-up to this, @4-x, are you on staging or production?

**Comment by flipsasser** [comment]
The fix and regression test for this is up
