### ISSUE TITLE
User role between author and editor

### ISSUE THREAD

**Issue by 4-x** [coyote-team/coyote#536]
Recent updates have changed the author role so that they cannot author descriptions for unassigned images and the editor role can now approve any descriptions, so there is no user who is able to freely author descriptions without the ability to also publish them.

**Comment by sinabahram** [comment]
@4-x  technically, that was the intent all along during Coyote dev, but this was left as a bug, which has turned into a feature on your end. Understandable, but just offering context.

The issue is that descriptions really are part of a workflow involving assignment. The granularity you are asking for; therefore, would be as follows. Tell me if this addresses your concern.

Authors can self-assign, and only self-assign, resources. Any/all other assignments are editor and above.

**Comment by 4-x** [comment]
@sinabahram That is a brilliant solution for my issue if you believe it would not present issues for teams relying on your intended assignment workflow.

**Comment by flipsasser** [comment]
We captured this as an organization setting and it's done!
