### ISSUE TITLE
Minor bug: search title field error 

### ISSUE THREAD

**Issue by alavatelliMCA** [coyote-team/coyote#56]
When I search "ebony", it reverts to the search I did earlier:
![screen shot 2016-10-21 at 5 27 48 pm](https://cloud.githubusercontent.com/assets/8040710/19613708/d7487d0c-97b3-11e6-9569-48c525e07485.png)

but if I search something that procures results it updates "light":
![screen shot 2016-10-21 at 5 29 32 pm](https://cloud.githubusercontent.com/assets/8040710/19613729/fa72ddc2-97b3-11e6-972c-86ecda2cd3f1.png)

Also, on our website the field Coyote calls `title` is what we call `caption`

**Comment by seeReadCode** [comment]
@alavatelliMCA
1. I can't replicate the main issue here of Coyote searching for a previous query instead of the latest query. Please provide exact steps.
2. I don't understand what you mean by "light" here.
3. Our taxonomy of `caption` versus `title` is a bit confused.  @sinabahram can I just switch us from title to caption across the board?

**Comment by seeReadCode** [comment]
The core issue should be fixed now.

**Comment by alavatelliMCA** [comment]
To clarify, if you search for something that has no results the field reverts to the contents of the previous search. I seach `ebony`, it procures 0 and displays `Kerry untitled` in the search field (my previous search). However when I search `light` the field maintains that content and displays results.

HOWEVER, I have investigated search further and find search to be misconfigured.

It seems to search as exact phrase (including ? Which is definitely incorrect, see the single result of searching on `Kerry James Marshall, Untitled` *which is an error it should also be italic*

I just tried searching `Kerry Untitled` and received 0 results, when Kerry James Marshall has several works that are Untitled, so then I tried to match phrase searching `Kerry James Marshall, Untitled` I get 1 result when it should be 7 even if searching on exact phrase instead of ANY–
![screen shot 2016-10-24 at 2 33 39 pm](https://cloud.githubusercontent.com/assets/8040710/19661113/0b3791f2-99f8-11e6-8304-17c110270346.png)

Results for `Kerry` using page search to highlight 7 results:
![screencapture-coyote-mcachicago-org-images-1477337839273](https://cloud.githubusercontent.com/assets/8040710/19660970/85b24d6a-99f7-11e6-9221-b5efff32cdc8.png)

**Comment by seeReadCode** [comment]
The search for `Kerry James Marshall, _Untitled` returns 33 results.  The field is searching across Markdown text (which is how it's stored in the DB).  

Also, the core issue has been fixed as far as I can tell.

**Comment by alavatelliMCA** [comment]
Right, I realized that was what was happening (though not knowing it was Markdown). Search should be based on `AND` to make images more findable, exact phrase searching really makes trouble for finding results, especially when you don't know the text styling.

It's also a high expectation for regular users to know that search only works with exact phrase so they can't simply search `Kerry Untitled`, much less understand Markdown.

If this is something that we have to put down as a future enhancement I'll add it to that list.

**Comment by seeReadCode** [comment]
@alavatelliMCA then let's move that request to another issue and close this one.  Making search both fuzzy and run across multiple fields will likely mean we need to start an indexing service (ie. not a quick fix).  

Also, it might make sense to consolidate our "not now but later" asks and enhancements into one issue titled Backlog.  That way we won't have to search across multiple issues to figure out what lies ahead.  When we are ready to work on the individual enhancements, then we can break them out as separate issues.  Keeping the issues orderly will at least help me keep a clear sense of what needs to be done sooner rather than later.  What do you think?

**Comment by alavatelliMCA** [comment]
As for search, is caption not imported as a single field? I think there is further enhancement to be discussed #53, but for this case what I am seeking is a simple modification to be able to use multiple keywords instead of an exact phrase as it is very hard to find objects that way.

e.g. knowing to type out `Kerry James Marshall, _Untitled` rather than `Marshall Untitled` hinders the efficiency usefulness of searching the captions field. Now that we know that it is searching a field written in markdown we can probably work around it, but in some cases will hinder discovery.

Totally agree on the approach to issues - this has been serving as the functionality backlog #58 and can be renamed as such.

**Comment by seeReadCode** [comment]
Ok, I think I've got space-delimited `AND`-style searching working.  Give it a spin!

**Comment by alavatelliMCA** [comment]
Love it.

**Comment by sinabahram** [comment]
Switching us “to caption” is perfectly fine. title has a specific definition, and one we should not be using anywhere.
