### ISSUE TITLE
API authentication documentation

### ISSUE THREAD

**Issue by jbenoit98** [coyote-team/coyote#569]
Hi, 
I'm looking for some documentation on the api. I saw a few services for Representations and Resources, but looking for Authentication to be able to create a session as needed. 
Thanks

**Comment by sinabahram** [comment]
Hi there, and thanks so much for the interest. Since Coyote is traditionally used as a hosted service, we are at the phase where we're working with folks individually that are wanting to use the service so we can control hosting/service costs. Happy to set up that conversation if that's of interest. Also, completely happy to provide you an opportunity to work and play with a staging environment, and additionally work things out for production depending on organization size and more. Perhaps an email conversation makes more sense?

So excited to have your interest in the platform.

**Comment by sinabahram** [comment]
Followed up over email.
