### ISSUE TITLE
Improve tag display on image index

### ISSUE THREAD

**Issue by alavatelliMCA** [coyote-team/coyote#68]
- [ ] Remove the display of tag cloud.
- [ ] Tags in search should be dropdown quantity displayed after the tag in parens:

edited by @seereadcode 2017/03/22

---

At the bottom of every list view one finds these same links labeled `Art "1" kjm "1" `

![screen shot 2016-12-22 at 12 36 16 pm](https://cloud.githubusercontent.com/assets/8040710/21436758/c5d32b04-c845-11e6-9c62-4837479bfae6.png)

**Comment by seeReadCode** [comment]
@alavatelliMCA those are tags with counts.  I imagine we'd rather they read something like: art(1), kjm(1).  If you click either tag, you will see the images that have the tag.  Edit the image and remove the tag, and it'll no longer display.

**Comment by alavatelliMCA** [comment]
Your explanation makes sense–However, this appears at the bottom of all views. Does this mean if we start using the tagging feature more all tags will start appearing on all pages at the bottom with counts in quotes? perhaps it is just a formatting discussion.

**Comment by seeReadCode** [comment]
They display on all variations of the `/images` index but that tag cloud shouldn't appear on any other pages.  But yes, if you use more tags, they will display there.

**Comment by alavatelliMCA** [comment]
Remove the display of tag cloud.
Tags in search should be dropdown quantity displayed after the tag in parens:

`kjm (1)`

**Comment by subelsky** [comment]
@alavatelliMCA @sinabahram I found an easy way to make this change, but a plain-vanilla HTML dropdown box won't work well in this context. I believe it will be necessary to use a JavaScript extension such as jQuery select [demo'd here](http://labs.abeautifulsite.net/archived/jquery-multiSelect/demo/). But that would make the search page less accessible, non-semantic. Since I just started working on this I don't want to wade in and make a bunch of invasive changes. 

Would you be open to the possibility of keeping the tag cloud, but styling it a little more?

**Comment by subelsky** [comment]
@sinabahram I believe this jQuery plugin would serve:

https://a11y.nicolas-hoffmann.net/autocomplet-list/

It looks like it would be accessible, but I'm not yet trained to know for sure :-)

**Comment by sinabahram** [comment]
I’m familiar with that one, but it needs some serious help.

 

Currently, no notification that suggestions are available, wrapping the list is super iffy, etc.

**Comment by sinabahram** [comment]
I want to add this resource here for us to consult.

 

Anatomy of an Accessible Auto Suggest

http://uxmastery.com/anatomy-of-an-accessible-auto-suggest/

 

I’m not claiming that’s perfect, but it covers a whole lot of the basics. Super happy to discuss further.
