### ISSUE TITLE
Create basic system admin screen

### ISSUE THREAD

**Issue by subelsky** [coyote-team/coyote#97]
@sinabahram what are the key 2-3 things you'd like to see here? You mentioned password reset, anything else?

Can we use the app's existing ACLs to restrict access to this screen or do you want to add a new role for superusers?

**Comment by sinabahram** [comment]
I think that a super-user role is appropriate here, but I would be ok with trialing it in admin access for now, so that we can get things working, since restricting access can always be a progressive enhancement.

 

Password reset makes sense

 

It would also be incredibly helpful to have access to environmental variables here, though. Right now, the environment of the installed location matters a great deal for all sorts of fields from username/pass info for DBs to IP addresses, etc. (having access to that on such a backend screen would modernize this approach a lot, I feel).

 

Also, we’ve discussed this cron-job approach. Would this type of screen be where such a thing could be managed/configured?

 

Any thoughts on your end for other things that could live here?

**Comment by subelsky** [comment]
A lot of these problems could be solved by implementing a modern devops architecture. I need to dig further into how the current system is deployed etc to be able to say more. But for example if Coyote were hosted on Heroku you would instantly have access to all `ENV` and could change them w/o a reboot

**Comment by subelsky** [comment]
Subsumed by #111
